### ISSUE TITLE
Download path is wrong

### ISSUE THREAD

**Issue by felipe1982** [voxpupuli/puppet-jira#111]
Error: curl  -f -L -o /opt/staging/jira/atlassian-jira-7.0.5.tar.gz http://www.atlassian.com/software/jira/downloads/binary//atlassian-jira-7.0.5.tar.gz returned 22 instead of one of [0]
    Error: /Stage[main]/Jira::Install/Staging::File[atlassian-jira-7.0.5.tar.gz]/Exec[/opt/staging/jira/atlassian-jira-7.0.5.tar.gz]/returns: change from notrun to 0 failed: curl  -f -L -o /opt/staging/jira/atlassian-jira-7.0.5.tar.gz http://www.atlassian.com/software/jira/downloads/binary//atlassian-jira-7.0.5.tar.gz returned 22 instead of one of [0]

Should be `https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.0.5-jira-7.0.5-x64.bin`

**Comment by rhoml** [comment]
@felipe1982 have you tried modifying `$format` to `bin` instead of tar.gz?

**Comment by felipe1982** [comment]
I get an error when changing format.

```
  class {'jdk_oracle':
    version => '8',
    version_update => '51',
    version_build => '16',
  } ->
  class {'jira':
    # downloadURL => 'https://downloads.atlassian.com/software/jira/downloads/',
    format      => 'bin',
    javahome    => '/opt/java_home',
    version     => '7.0.5',

    db          => 'oracle',
    dbtype      => 'oracle10g',
    dbserver    => 'fred.example.com.au',
    dbport      => '1521',

    dbuser      => 'jira',
    dbpassword  => 'jira',
    dbname      => 'D11',

    proxy       => {
      scheme    => 'http',
      proxyName => 'jiratest.example.com.au',
      proxyPort => '80'
    },


  } ->
  class {'jira::facts': }
```

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: staging::extract: unsupported file format atlassian-jira-7.0.5.bin. at /etc/puppet/modules/staging/manifests/extract.pp:102

**Comment by rhoml** [comment]
So i tried to download the Jira tar.gz from https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.0.5-x64.tar.gz and it works properly. I don't have clear understanding why it is downloading from 
http://www.atlassian.com/software/jira/downloads/binary//atlassian-jira-7.0.5.tar.gz in your case above since the only place where I see that download url is on the specs.

**Comment by rhoml** [comment]
So i tried to download the Jira tar.gz from https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.0.5-jira-7.0.5.tar.gz and it works properly. I don't have clear understanding why it is downloading from 
http://www.atlassian.com/software/jira/downloads/binary//atlassian-jira-7.0.5.tar.gz in your case above since the only place where I see that download url is on the specs.

**Comment by felipe1982** [comment]
I have removed format and downloadURL.

Now module tries to fetch
```
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-7.0.5.tar.gz
```
but should fetch 
```
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.0.5-jira-7.0.5.tar.gz
```

**Comment by philchristensen** [comment]
I'm having the same issue. My manifest reads as follows:

```
  class { '::jira':
    javahome     => '/usr/lib/jvm/default-java',
    version      => '7.1.1',
    installdir   => "/opt/jira",
    homedir      => "/var/lib/jira",
    proxy        => {
      scheme     => 'https',
      proxyName  => 'prod-project.aws.logicworks.net',
      proxyPort  => '443',
    },
    dbuser       => "jira",
    dbpassword   => "**********",
    dbserver     => "prod-jira-db.aws.logicworks.local",
    enable_connection_pooling => true,
    require      => Class['automation::common::java']
  }
```

I've read and re-read the source and I cannot figure out why this is trying to download the link from 

```
http://www.atlassian.com/software/jira/downloads/binary//atlassian-jira-7.1.1.tar.gz
```

**Comment by philchristensen** [comment]
Aha! I found a workaround at least:

```
  class { '::jira':
    javahome     => '/usr/lib/jvm/default-java',
    product      => 'jira-software-7.1.1-jira',
    version      => '7.1.1',
```

**Comment by AlexanderNZ** [comment]
Thanks @philchristensen - your work around works well for jira versions between 7.1.1 and 7.1.4.
Hopefully this issue gets some love soon :)

**Comment by sacres** [comment]
iApparently we need a magic regex for this, this isn't scalable nor maintainable as is. I'll see how far I get with that.

**Comment by olevole** [comment]
Up issue. 

For 7.1.9 we need to change postfix:

~~~
diff -ruN install.pp-bak install.pp 
--- install.pp-bak      2016-08-08 13:03:34.220422399 +0300
+++ install.pp  2016-08-08 13:10:16.988347547 +0300
@@ -50,7 +50,7 @@
   if ((versioncmp($jira::version, '7.0.0') < 0) or ($jira::product_name == 'jira-core')) {
     $file = "atlassian-${jira::product_name}-${jira::version}.${jira::format}"
   } else {
-    $file = "atlassian-${jira::product_name}-${jira::version}-jira-${jira::version}.${jira::format}"
+    $file = "atlassian-${jira::product_name}-${jira::version}.${jira::format}"
   }
 
   if ! defined(File[$jira::extractdir]) {
~~~

Can anyone fix this problem ?
