### ISSUE TITLE
Unable to provide own configuration options in jira-config.properties

### ISSUE THREAD

**Issue by oysteing** [voxpupuli/puppet-jira#112]
After commit e2f929f820b03af7d81c508714e298d533841bec, I'm not able to set custom configuration in jira-config.properties anymore, as the file is now controlled by puppet-jira.

There are no options for providing own properties, and the only reason for managing this file was to disable WebSudo.

A number of solution would be acceptable to most users:
- Don't manage the file unless the default setting is overridden
- Manage the file with Augeas
- Allow users to provide a map of key/value pairs to be appended to the file

**Comment by igalic** [comment]
@oysteing all of those sound like sensible options.
i think i'd prefer the third.
would you like to take a stab at providing a patch?

**Comment by oysteing** [comment]
Sure. I've created pull request #113.
