### ISSUE TITLE
Jira don't want to use my created database

### ISSUE THREAD

**Issue by Floryder** [voxpupuli/puppet-jira#117]
Hey there,

i become desperate with die jira-module. 
How will jira write in the created Database "jira". In my case the used parameteres are only used for the dbconfig.xml. If I watch the MySQL DB, it is empty. And then I tried the config.sh from the bin-directory. There I saw that Jira is still using the default Database. If I change the DB-settings in this config jira will work. But this should work as default in my opinion.

It would be nice if someone could support me with my puppet-manifest which looks like this:

``` puppet
class { 'jira':
         version     => '6.3.13',
         installdir  => '/opt/atlassian-jira',
         homedir     => '/var/atlassian-jira/jira-home',
         user        => 'jira',
         group       => 'root',
         db => 'mysql',
         dbtype => 'mysql',
         dbuser => 'jira',
         dbname => 'jira',
         dbpassword  => 'test',
         dbserver    => 'localhost',
         javahome    => '/opt/java/jdk1.7.0_21/',
         mysql_connector_URL => 'https://dev.mysql.com/downloads/file/?id=460362',
         proxy          => {
            scheme       => 'https',
            proxyName    => 'localhost',
            proxyPort    => '8443',
         }
    }
```

Greetings,
Florian

**Comment by oranenj** [comment]
This issue is old enough that I'm just going to close it. Chances are, this will work better with current master.
