### ISSUE TITLE
JIRA 7.1.x compatibility

### ISSUE THREAD

**Issue by jared-di** [voxpupuli/puppet-jira#120]
New line needs to be added to the dbconfig.xml file when using MSSQL

``` html
<validation-query>select 1</validation-query>
```

More information here: https://jira.atlassian.com/browse/JRA-59768

**Comment by igalic** [comment]
@jared-di would you like to provide a patch for that?

**Comment by sacres** [comment]
This line should be added according to the code: 
[CONFIG](https://github.com/voxpupuli/puppet-jira/blob/master/manifests/config.pp#L28) &
[DBCONFIG SQLSERVER](https://github.com/voxpupuli/puppet-jira/blob/master/templates/dbconfig.sqlserver.xml.erb#L16)
Isn't this the case with the current release now @jared-di ?

**Comment by oranenj** [comment]
I think this was a JIRA bug and explicitly specifying validation queries should not be necessary nowadays.
