### ISSUE TITLE
Basic usage - Could not find class staging.

### ISSUE THREAD

**Issue by djmentos** [voxpupuli/puppet-jira#121]
Hello,

I encountered an issue while testing module under Profile/Role architecture. 

/manifests/site.pp:
> node 'jira.intranet' {
>   include role::jira
> }

/modules/role/manifests/jira.pp:
> class role::jira {
>   notify { 'This is a JIRA Server role': }
>   include profile::jira_instance
> }

/modules/profile/manifests/jira_instance.pp:
> class profile::jira_instance {
>   notify { 'This is a JIRA instance profile': }
> 
>   file { '/opt/atlassian':
>      ensure => 'directory',
>    }

>   class { '::jira':
>     javahome    => '/opt/java',
>   }

>   include ::jira::facts
> }

Puppet returns:

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class staging for jira.intranet on node jira.intranet

Is it a bug, or just I am doing something wrong?

**Comment by jyaworski** [comment]
Do you have [puppet-staging](https://github.com/voxpupuli/puppet-staging) in your environment?

**Comment by djmentos** [comment]
That's right, forgot to copy it. Sorry for unnecessary trouble.
