### ISSUE TITLE
Use service_provider for init management

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-jira#124]
We should use service_provider to ship init files.

``` shell
[root@puppetdb2 ~]# facter -p service_provider operatingsystem operatingsystemmajrelease
operatingsystem => CentOS
operatingsystemmajrelease => 6
service_provider => redhat

[root@rundeck ~]# facter -p service_provider operatingsystem operatingsystemmajrelease
operatingsystem => CentOS
operatingsystemmajrelease => 7
service_provider => systemd
```

**Comment by igalic** [comment]
i'm still not sure about service_provider's usefulness

on my 16.04 machine it's still reporting debian, not systemd…

**Comment by jyaworski** [comment]
@igalic sounds like a bug for facter.

**Comment by igalic** [comment]
or puppet, rather, given how the fact is implemented: https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/facter/service_provider.rb

**Comment by asasfu** [comment]
This is because the version of puppet you're on doesn't support Ubuntu 16.04 so it hasn't made systemd.rb the provider for service...  That's truly how that fact operates.

**Comment by igalic** [comment]
4.3.2 :O

**Comment by confiq** [comment]
default puppet version in ubuntu 16.04 is 3.8.5 and that version does not support `service_provider`

**Comment by jyaworski** [comment]
We can hold on this until everything we support has it.

**Comment by igalic** [comment]
hehe, it's not like we haven't been holding onto this for a year already

**Comment by asasfu** [comment]
The wait is strong in here!

**Comment by bastelfreak** [comment]
as a sidenode, Vox Pupuli only supports puppet 4.8 and newer, and if the module has data-in-module it is 4.9. if anybody provides a PR for this I'm happy to merge it.

**Comment by ekohl** [comment]
23242f9f7a68f6d0728bc2c3d7b1198570f69b34 dropped support for sysvinit which makes this issue moot.
