### ISSUE TITLE
how can I use this module to deploy jira with servicedesk?

### ISSUE THREAD

**Issue by nomoresecrets** [voxpupuli/puppet-jira#134]
I tried defining product => 'servicedesk' but it looks like the download fails.

I can see a file "atlassian-servicedesk-3.1.2.tar.gz_..." under /tmp. The correct filename seems to be "atlassian-servicedesk-3.1.2-jira-7.1.2.tar.gz".

Best regards,

Denny

**Comment by nomoresecrets** [comment]
Closed. I simply added ServiceDesk within the deployed Jira instance.

**Comment by ubellavance** [comment]
Hi,

I'm planning on using this module to deploy Jira Software and Service Desk. Are you still using it this way?  Any problems up to now? How did the upgrades went?

Thanks,

**Comment by ubellavance** [comment]
Hi,
Thanks for your input.  Are the upgrades of both Jira Service Desk and Jira Software done via puppet?

**Comment by nomoresecrets** [comment]
software gets updated via puppet and servicedesk via web-ui of jira
