### ISSUE TITLE
Error: Could not autoload puppet/parser/functions/scope_defaults:

### ISSUE THREAD

**Issue by Dharmender-Singh** [voxpupuli/puppet-jira#136]
Hi,

I am facing an issue while using this module. Following is the Error : 

  Error: Could not autoload puppet/parser/functions/scope_defaults: /tmp/ki
tchen/modules/staging/lib/puppet/parser/functions/scope_defaults.rb:2: syntax er
ror, unexpected ':', expecting ')'
         newfunction(:scope_defaults, type: :rvalue, doc: <<-EOS
                                    ^
       /tmp/kitchen/modules/staging/lib/puppet/parser/functions/scope_defaults.r
b:6: syntax error, unexpected ')', expecting kEND
         ) do |arguments|

Could you please help me to solve this error.

Thanks & Regards
Dharmender

**Comment by jyaworski** [comment]
Are you using Ruby 1.8.7?

**Comment by Dharmender-Singh** [comment]
Yes, That's right.

**Comment by jyaworski** [comment]
We dropped support for ruby 1.8.7. That error you're seeing is related to the new hash syntax present in 1.9 and beyond.

**Comment by Dharmender-Singh** [comment]
Ok..Thanks
