### ISSUE TITLE
Seems to be obsolete - JIRA 7.1.4

### ISSUE THREAD

**Issue by ivantichy** [voxpupuli/puppet-jira#137]
I tried to used this module do install actual JIRA version 7.1.4 but even wget did not download installation files. Is this module obsolete?

**Comment by jjthiessen** [comment]
Jira 7 support was claimed to have been added in module version 2.0.0 (2016-05-26). I understand that your issue/comment was from before then (2016-04-12). Have you since tried with the 2.0.0 release of the module?

**Comment by ivantichy** [comment]
No, I rather created Docker image: https://hub.docker.com/r/ivantichy/jira/

**Comment by sacres** [comment]
This module definitely supports 7 (as well as upgrading from 6 to 7).

**Comment by ivantichy** [comment]
Maybe today.. :)

**Comment by oranenj** [comment]
Doing issue cleanup, this one is past its best-before state
