### ISSUE TITLE
HTTP to HTTPS redirect

### ISSUE THREAD

**Issue by dkossako** [voxpupuli/puppet-jira#138]
Hello,

is it possible to redirect HTTP requests to HTTPS using this module?

**Comment by jyaworski** [comment]
Initial findings: no.

We recommend using apache/nginx for this. We have this in the docs:

https://github.com/voxpupuli/puppet-jira#jira-prerequisites

Whilst not required, for production use we recommend using nginx/apache as a reverse proxy to JIRA. We suggest using the jfryman/nginx puppet module

**Comment by djmentos** [comment]
I found this setting:
https://github.com/voxpupuli/puppet-jira#tomcat_redirect_https_port

But it doesn't work (looks is not implemented):
`templates/server.xml.erb:        <Connector port="<%= @tomcatPort %>"
templates/server.xml.erb:                   <%- if @tomcatAddress -%>
templates/server.xml.erb:                   address="<%= @tomcatAddress %>"
templates/server.xml.erb:                   maxThreads="<%= @tomcatMaxThreads %>"
templates/server.xml.erb:                   acceptCount="<%= @tomcatAcceptCount %>"
templates/server.xml.erb:<% if @tomcatNativeSsl -%>
templates/server.xml.erb:                   redirectPort="<%= @tomcatHttpsPort %>"`

Shouldn't be:
`redirectPort="<%= @tomcat_redirect_https_port %>"`?

**Comment by djmentos** [comment]
There is missing change in WEB-INF/web.xml to allow HTTP -> HTTPS redirect, like described here:

https://confluence.atlassian.com/adminjiraserver071/running-jira-applications-over-ssl-or-https-802593051.html

**Comment by sacres** [comment]
@djmentos This works as expected.
`To be used with tomcat_native_ssl. ` is the salient qualifier in the you're referring to and also requires addressing JKS. 
If you would like a production example of how to proxy via apache/nginx (SSL termination at proxy frontend and 80 -> 443 redir), I can provide you with that.

**Comment by ericlaflamme** [comment]
Yes, it was working on jira6

jira::tomcat_native_ssl:         true
jira::tomcat_redirect_https_port: '443'

All request sent to 80 and redirect to 8080 per iptables will be redirect to port 443. By default it will redirect to 8443 because it's the real port. Then I redirect 443 to 8443 with iptables.

I might work on the code for the web.xml for jira7.1

**Comment by oranenj** [comment]
I'm going to say that this is out of scope for now, given how old this issue is, and people really ought to be using a reverse proxy for this anyway.
