### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/puppet-jira#143]
There has been a lot of work done on this module since the last release, 1.3.0, in Aug of 2015. It looks like it is probably time for a new release.

* Are there urgent PRs/issues that need resolved first?
* Should the next version be 1.4.0 or 2.0.0?

**Comment by igalic** [comment]
once we have a release-pipeline for this module, releasing a new version with urgent issues fixed is easy. We'll know which version to release, when we start writing the Changelog ;)

**Comment by bastelfreak** [comment]
we just did a fresh modulesync, good time for a release.

**Comment by bastelfreak** [comment]
released
