### ISSUE TITLE
Oracle connection string incorrect

### ISSUE THREAD

**Issue by noemif** [voxpupuli/puppet-jira#146]
In init.pp line 215, it should be
`"jdbc:${db}:thin:@//${dbserver}:${dbport}/${dbname}"`
instead of
`"jdbc:${db}:thin:@${dbserver}:${dbport}:${dbname}"`

Just tested this with Jira 7.1.7 and Oracle Database 11g Enterprise Edition Release 11.2.0.3.0

**Comment by alexjfisher** [comment]
@noemif https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html suggests the current code is correct.  Could you double check?

**Comment by noemif** [comment]
Thanks for researching this issue, Alex !

I checked a few docs online, too, and wasted quite a bit of time on that.
In the end, the syntax I submitted above:
- is what I had in my current (working) jira prod config
- is what was spat out by Atlassian's own config tool (${webappdir}/bin/config.sh)
- is what ultimately got my new jira instance to connect to the DB
So it is puzzling, but the proof is in the pudding ;-)

I understand if you're not comfortable changing this without further testing though.
At least, the existence of this open issue might help someone else with similar problems, and they might submit their experience here.

Cheers,
Noemi

**Comment by jarshwah** [comment]
The difference is between whether the dbname is a SID or Service Name. Both need to be supported depending on how oracle server has been deployed.

**Comment by TJM** [comment]
On a positive note, if you end up here and need to customize the jdbc connection url, you can do that with the `dburl` parameter.

**Comment by oranenj** [comment]
I'll close this as a duplicate-ish of #283
