### ISSUE TITLE
Can't create parent directories if they dont exist

### ISSUE THREAD

**Issue by krinkere** [voxpupuli/puppet-jira#150]
While README file states that you can do something like this
homedir      => '/opt/atlassian-jira/jira-home',

it wont work if atlassian-jira does not exist

**Comment by krinkere** [comment]
As a workaround for now... 
groupadd jira
useradd jira -g jira

mkdir -p /opt/atlassian/jira
chown -R jira:jira /opt/atlassian/
chmod -R 755 /opt/atlassian/

mkdir -p /var/atlassian/application-data/jira
chown -R jira:jira /var/atlassian/
chmod -R 755 /opt/atlassian/

then in actual manifest

class { 'jira':
  version    => '6.4.13',
  installdir => '/opt/atlassian/jira',
  homedir    => '/var/atlassian/application-data/jira',
}

**Comment by jyaworski** [comment]
This is assuming the directory structure exists from the package being installed, IIRC.

**Comment by krinkere** [comment]
i guess it was not clear... 
documentation said to provide the install/home directories and by looking at init.pp it would even create jira user and group for you, which is nice - so i assumed it would create parent directories too if needed. 

But it is a small thing with a workaround. Perhaps documentation fix is all that is needed here.

**Comment by jyaworski** [comment]
Creating directory structures is hard in puppet. Well, hard to do correctly. https://forge.puppet.com/pltraining/dirtree is the most elegant way I've seen it done to-date. @bastelfreak what do you think?

**Comment by juniorsysadmin** [comment]
I'm not in favor of making dirtree a dependency

**Comment by bastelfreak** [comment]
Dealing with directories is always a bit painful. @juniorsysadmin why shouldn't we make it as a dependency?

**Comment by krinkere** [comment]
+1 for dependency. At least that's what I end up doing.

**Comment by juniorsysadmin** [comment]
@bastelfreak I would rather that we do a conditional ```ensure_resource()``` for the parent directory/directories, but only if we are using the defaults - which I assume reflect what directories the upstream Jira binary installer creates
eg.
```
if $homedir == '/opt/atlassian-jira/jira-home' {
  ensure_resource(file jira-home parent(s))
}
```
