### ISSUE TITLE
Unable to install JIRA 7.2.x.

### ISSUE THREAD

**Issue by djmentos** [voxpupuli/puppet-jira#159]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.5
- Ruby: 2.3.1
- Distribution: Ubuntu 16.04
- Module version: latest

### How to reproduce (e.g Puppet code you use)
> class { '::jira':
>     version       => '7.2.1',
>     checksum      => '9af0fec75793d12c88055dc045121f89',

### What are you seeing
```
# cat /tmp/atlassian-jira-software-7.2.1-jira-7.2.1.tar.gz_a23a1704a09915a2a12d5779de78c65620160907-50475-1qg0kb8 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /software/jira/downloads/atlassian-jira-software-7.2.1-jira-7.2.1.tar.gz was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at downloads-origin.atlassian.com Port 80</address>
</body></html>
```

### What behaviour did you expect instead
Installed JIRA.

### Output log
> Error: Download file checksum mismatch
> Error: /Stage[main]/Jira::Install/Archive[/tmp/atlassian-jira-software-7.2.1-jira-7.2.1.tar.gz]/ensure: change from absent to present failed: Download file checksum mismatch

### Any additional information you'd like to impart
Atlassian has changed name convention. New URL:
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.2.1.tar.gz

**Comment by Skarzee** [comment]
Can confirm, naming convention needs to be adhered too. You can unconventionally and incorrectly wget the file and manually extract it to your $install_dir if you're looking for a work around, may need a systemctl daemon-reload, but a PR is needed to update the repository.

**Comment by djmentos** [comment]
Pull request with fix has been merged.

**Comment by alexjfisher** [comment]
@djmentos Thanks.  Fixed in https://github.com/voxpupuli/puppet-jira/pull/160
