### ISSUE TITLE
Connector class incompatibility since JIRA 7.3.0.

### ISSUE THREAD

**Issue by dkossako** [voxpupuli/puppet-jira#213]
Hello, 

since JIRA 7.3.0 Atlassian has changed name of http connector class and puppet-jira module is incompatible. More info about the change:
https://www.reddit.com/r/jira/comments/5m1n8z/fyi_ssl_jira_fail_in_730_unless_you_change_your/

- Puppet: 3.8.5
- Ruby: 2.3.1
- Module version: 3.2.0

**Comment by markleary** [comment]
Fixed in #219.  You will need to manually specify `$tomcat_protocol_ssl => "org.apache.coyote.http11.Http11NioProtocol"` to maintain compatibility with older versions.  Previous pull request for this issue breaks compatibility with older versions.

**Comment by vrowley** [comment]
Would it be possible for someone to set the tomcat_protocal_ssl so it defaults to "jira::tomcat_protocol                org.apache.coyote.ajp.AjpNioProtocol"

This would save anyone doing a fresh install of 7.5.0 from banging their head against the wall.

**Comment by bastelfreak** [comment]
@vrowley could you provide a patch for this?

**Comment by markleary** [comment]
I think the best way to do this would be to set $tomcat_protocol_ssl based on $version.  I should be able submit a pr in the next couple days if @vrowley doesn't want to.

**Comment by markleary** [comment]
Ok, done #225.

**Comment by oranenj** [comment]
PR Fixing this is merged, closing.
