### ISSUE TITLE
Update download URL logic

### ISSUE THREAD

**Issue by cpepe** [voxpupuli/puppet-jira#218]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)
Set jira version to 7.0.11

## What are you seeing
This module produces the download URL https://downloads.atlassian.com/software/jira/downloads//atlassian-jira-software-7.0.11-jira-7.0.11.tar.gz which is invalid.

It produces a similar URL for 7.0.4 which is correct.

## What behaviour did you expect instead
The url should be https://downloads.atlassian.com/software/jira/downloads//atlassian-jira-software-7.0.11.tar.gz

## Output log
Error: Execution of '/bin/curl https://downloads.atlassian.com/software/jira/downloads//atlassian-jira-software-7.0.11-jira-7.0.11.tar.gz -o /tmp/atlassian-jira-software-7.0.11-jira-7.0.11.tar.gz_20170713-25336-l5iy8w -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found
Error: /Stage[main]/Jira::Install/Archive[/tmp/atlassian-jira-software-7.0.11-jira-7.0.11.tar.gz]/ensure: change from absent to present failed: Execution of '/bin/curl https://downloads.atlassian.com/software/jira/downloads//atlassian-jira-software-7.0.11-jira-7.0.11.tar.gz -o /tmp/atlassian-jira-software-7.0.11-jira-7.0.11.tar.gz_20170713-25336-l5iy8w -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found

## Any additional information you'd like to impart
Line 51 in puppet-jira/manifests/install.pp sets the cut-off for the new url as 7.1.9 but that leaves 7.0.11 out. I will attempt to come back and test the other versions between 7.0.11 and 7.1.9 to see if line 51 can updated to make the cutoff 7.0.11 instead of 7.1.9 but I have not checked beyond this version at the moment.

**Comment by cpepe** [comment]
Since users are likely to want to upgrade to newer versions of JIRA the workaround that I plan to use is to upgrade to 7.0.4 and then on to 7.x. The only potential issue is a feature or add-on requirement to go to 7.0.11 instead of 7.0.4 but this is unlikely to crop up.

**Comment by vrowley** [comment]
They changed the file name between 7.0.10 and 7.0.11, so will this work from 7.0.10 to 7.x?

**Comment by cpepe** [comment]
from the release logs there was 7.0.10 and 7.0.11 before the 7.1 series. The new filename seems to have been introduced with 7.0.11 so "line 51" above should use 7.0.11 instead of 7.1.9 to select the URL generator.

**Comment by vrowley** [comment]
Just a quick note to say thank you.  Last night I changed my .yaml to reference 7.1.10.  I saw nullPointer errors in the logs and rage quit.  :-P
When I looked at it this morning, it was up and running.  Woo-hoo!  I obviously have errors in the logs to chase down, but at least it's operational again.

**Comment by cpepe** [comment]
:-) my pleasure. I was pretty happy to find this module. Glad to contribute if only in a small way.

**Comment by ekohl** [comment]
Is this still an issue or was it fixed?

**Comment by cpepe** [comment]
Because the affected versions are so old we haven't looked back into this.
JIRA 7.0 went end of life on October 6 and people using this module can
simply upgrade to 7.0.11 instead of 7.0.4. They will be headed for JIRA 7.5
anyway so it shouldn't be a blocker for most people.

**Comment by ekohl** [comment]
In that case I'm going to close this.
