### ISSUE TITLE
Proxy bypass HTTP connector requires AJP Protocol

### ISSUE THREAD

**Issue by eriksalinenike** [voxpupuli/puppet-jira#227]
Proxy bypass HTTP connector for tomcat requires the AJP protocol, however we are using Nginx as a reverse proxy.  Is there any way to set a bypass port using the HTTP/1.1 protocol?

`  if ! empty($ajp) {
    if ! has_key($ajp, 'port') {
      fail('You need to specify a valid port for the AJP connector.')
    } else {
      validate_re($ajp['port'], '^\d+$')
    }
    if ! has_key($ajp, 'protocol') {
      fail('You need to specify a valid protocol for the AJP connector.')
    } else {
      validate_re($ajp['protocol'], ['^AJP/1.3$', '^org.apache.coyote.ajp'])
    }
  }`

**Comment by oranenj** [comment]
I think master supports custom tomcat connectors nowadays, which might solve this problem.

I'll close this issue since it's getting old. :)
