### ISSUE TITLE
MySQL storage_engine problem

### ISSUE THREAD

**Issue by vrmerlin** [voxpupuli/puppet-jira#239]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.5
- Ruby: 2.0.0p648
- Distribution: Puppet Enterprise
- Module version: 3.4.0

## How to reproduce (e.g Puppet code you use)

```
  class { 'jira':
    version             => '7.8.1',
    installdir          => '/opt/atlassian-jira',
    homedir             => '/myatlassian/jira',
    db                  => 'mysql',
    dbtype              => 'mysql',
    dbname              => 'jiradb',
    dbuser              => 'jiradbuser',
    dbdriver            => 'com.mysql.jdbc.Driver',
    dbpassword          => 'XXX',
    dbserver            => 'localhost',
    javahome            => '/usr/java/default',
    jvm_xmx             => '3584m',
    jvm_xms             => '3584m',
    mysql_connector_version => '5.1.46',
  }
```

## What are you seeing

The file dbconfig.xml is being modified by Puppet to have this JDBC URL:

```jdbc:mysql://localhost:5432/jiradb?useUnicode=true&amp;characterEncoding=UTF8&amp;sessionVariables=storage_engine=InnoDB```

However, JIRA is coming up and complaining this: "The connection URL in your dbconfig.xml file contains the storage_engine parameter, which has been deprecated. This needs to be replaced with the default_storage_engine parameter."

## What behaviour did you expect instead

How do I change the sessionVariable to match what JIRA 7.8.1 is expecting?

**Comment by bastelfreak** [comment]
I just merged https://github.com/voxpupuli/puppet-jira/pull/216 which should fix this. I'm going to release a new version now. Please report back if it doesn't fix your issue.

**Comment by vrmerlin** [comment]
Yep, that fixed the issue! Thanks :-)
