### ISSUE TITLE
MySQL Connector is not installing with correct directory permissions

### ISSUE THREAD

**Issue by vrmerlin** [voxpupuli/puppet-jira#241]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.5
- Ruby: 2.0.0p648
- Distribution: Puppet Enterprise
- Module version: 3.4.1

## How to reproduce (e.g Puppet code you use)

I installed JIRA with this configuration (after a successful MySQL installation):

```
  class { 'jira':
    version             => '7.8.1',
    installdir          => '/opt/atlassian-jira',
    db                  => 'mysql',
    dbtype              => 'mysql',
    dbname              => 'jiradb',
    dbuser              => 'jiradbuser',
    dbdriver            => 'com.mysql.jdbc.Driver',
    dbpassword          => 'xxx',
    dbserver            => 'localhost',
    dbport              => '3306',
    javahome            => '/usr/java/default',
    jvm_xmx             => '3584m',
    jvm_xms             => '3584m',
    download_url        => 'http://localrepo:6000/atlassian',
    mysql_connector_version => '5.1.46',
    mysql_connector_url => 'http://localrepo:6000/atlassian',
  }
```

## What are you seeing

Everything seems to install right in Puppet, but JIRA starts up and complains it can't find the MySQL connector JAR file. I can see it DID install though,  in `/opt/MySQL-connector`.

## What behaviour did you expect instead

The problem appears to be that the JIRA module creates the permissions wrong for `/opt/MySQL-connector`. The directory is given permissions of `drwxr-x---` and is owned by root. This means user jira can't see inside the directory. When I manually change the permissions using `chmod a+rx /opt/MySQL-connector` and restart JIRA, then JIRA can see the database and things work fine.

Is there a workaround, or is it possible to get a new version of the JIRA module that sets the permissions correctly for /opt/MySQL-connector? I'd prefer it not be owned by user jira, as I'll be installing some other Atlassian tools on the same machine (and hopefully, they will use the same connector).

**Comment by lgooch** [comment]
This issue has recently caused me some pain as well so I've fixed the issue and opened a PR to merge the fix in.
