### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-jira#248]
this module once listed debian 7 in the metadata.json. We removed it because it's EOL. We need to check if recent debian versions work and add them back.

**Comment by dpisano** [comment]
I have been using version 2.0.0 for some time on Debian 8. I'm in the process of testing a newer version for module.

**Comment by ssanden** [comment]
i used this module with debian8 and debian9. 
today i updated the module from 3.5.2 to 4.0.0 on a debian9 jira staging environment. i upgraded jira to 8.3 - all worked pretty good.

**Comment by dpisano** [comment]
@ssanden Are you using the all in one version of the agent?

**Comment by ssanden** [comment]
@dpisano, right.. the "puppet-agent" package after installing the release-package directly from apt.puppetlabs.com. 
right now with puppet5 mostly on lxc btw..

**Comment by dpisano** [comment]
@ssanden I just did a clean install using version 4.0.0 of the module. I'm still seeing `/etc/facter/facts.d/jira_facts.rb` error on puppet runs.  I know that #158 has set out to fix this, but has stalled. I'm going to submit a PR with a fix that I have been using.

**Comment by oranenj** [comment]
I tried running the tests with Debian 10, but they seem to fail for whatever reason.

I don't see why this module wouldn't work on Debian, but unless someone steps up gets the tests running, it won't be officially supported in 5.0.0
