### ISSUE TITLE
jira user depends on install dir (unable to set home dir inside install dir as per example)

### ISSUE THREAD

**Issue by TJM** [voxpupuli/puppet-jira#255]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.2
- Ruby: ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
- Distribution: CentOS 7.5
- Module version: 3.4.1

## How to reproduce (e.g Puppet code you use)

```puppet
include jira
include jira::facts
```

```yaml
jira::version: 7.10.2
jira::javahome: /usr/java/default
jira::installdir: /opt/atlassian/atlassian-jira
jira::homedir: /opt/atlassian/application-data/jira-home
```

## What are you seeing

Failure, because of cross-dependencies. The user account cannot be created because "manage_home" is true and it can't create it's home dir, but the directory cannot be created because the user account cannot be created.

## What behaviour did you expect instead

I expected the user to be created and everything to work as planned ;)

Potential Solutions:

* The JIRA_HOME does not necessarily need to be the home directory of the jira user, perhaps that could be handled separately.
* The INSTALLDIR doesn't necessarily need to be owned by JIRAUSER
* Perhaps we could set manage_home to false, in certain circumstances?

## Output log

```
==> jira7: Error: Could not create user jira: Execution of '/sbin/useradd -c Jira daemon account -g 1001 -d /opt/atlassian/application-data/jira-home -p * -s /bin/true -u 1001 -m jira' returned 12: useradd: cannot create directory /opt/atlassian/application-data/jira-home
==> jira7: Error: /Stage[main]/Jira::Install/User[jira]/ensure: change from 'absent' to 'present' failed: Could not create user jira: Execution of '/sbin/useradd -c Jira daemon account -g 1001 -d /opt/atlassian/application-data/jira-home -p * -s /bin/true -u 1001 -m jira' returned 12: useradd: cannot create directory /opt/atlassian/application-data/jira-home
==> jira7: Warning: /Stage[main]/Jira::Install/File[/opt/atlassian/atlassian-jira]: Skipping because of failed dependencies
==> jira7: Warning: /Stage[main]/Jira::Install/File[/opt/atlassian/atlassian-jira/atlassian-jira-software-7.2.4-standalone]: Skipping because of failed dependencies
```

## Any additional information you'd like to impart

This is from the example documentation in README.md, but it is also affecting my customer's "normal" installation. They would like /apps/atlassian-jira-VERSION and JIRA_HOME set to /apps/jira.

**Comment by TJM** [comment]
@bastelfreak To fix this should we just modify the code to make "$install_dir" owned by root:root (0:0)? It doesn't need to be owned by jira:jira, because puppet creates the "destination" ($install_dir/atlassian-jira-VERSION-standalone) directory owned by jira before unarchiving.

**Comment by lgooch** [comment]
@TJM I've recently been caught out by this issue. Do you have any plans to fix this yourself or are you happy for me to pick this up?

**Comment by TJM** [comment]
@lgooch I used the workaround above in my "profile" for jira. :)
