### ISSUE TITLE
This logic does not allow Jira Service Desk to operate

### ISSUE THREAD

**Issue by cpepe** [voxpupuli/puppet-jira#259]
https://github.com/voxpupuli/puppet-jira/blob/41eeb5c06ade0295fdfcea4760b2f2e239d44cd7/templates/server.xml.erb#L35

The Jasper listener needs to be disabled for JSD as well, due to the namely logic the product must be defined as "servicedesk" whereas the other two are "jira-core", and "jira-software"

**Comment by cpepe** [comment]
Find the PR here: https://github.com/voxpupuli/puppet-jira/pull/260

**Comment by bastelfreak** [comment]
thanks for reporting and fixing this @cpepe !
