### ISSUE TITLE
Jira 7.12 needs relaxedPathChars & relaxedQueryChars

### ISSUE THREAD

**Issue by nambrosch** [voxpupuli/puppet-jira#269]
Jira 7.12 runs on tomcat 8.5 and needs additional connector parameters -

https://confluence.atlassian.com/jirakb/changing-server-xml-to-handle-requests-with-special-characters-958453799.html

Here's the new default connector -

```
<Connector
  port="8080"
  relaxedPathChars="[]|"
  relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"
  maxThreads="150"
  minSpareThreads="25"
  connectionTimeout="20000"
  enableLookups="false"
  maxHttpHeaderSize="8192"
  protocol="HTTP/1.1"
  useBodyEncodingForURI="true"
  redirectPort="8443"
  acceptCount="100"
  disableUploadTimeout="true"
  bindOnInit="false"
/>
```

Please provide a way to add relaxedPathChars and relaxedQueryChars.  Thanks!

**Comment by nambrosch** [comment]
something like this should work @ https://github.com/voxpupuli/puppet-jira/blob/master/templates/server.xml.erb#L77

```
<% if @version >= 7.12 -%>
                   relaxedPathChars="[]|"
                   relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"
<% end -%>
```

**Comment by vonex-tim** [comment]
As a workaround, you can append these attributes to the proxy parameter, eg:
proxy => {"scheme":"https","proxyName":"<Hostname>","proxyPort":"443","relaxedPathChars":"[]|","relaxedQueryChars":"[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"}

**Comment by alexvanvucht** [comment]
As a workaround you can append these to the proxy parameter, eg:
proxy => { 'scheme' => 'https',
'proxyName' => $facts['hostname'],
'proxyPort'=>'443',
'relaxedPathChars'=>'[]|',
'relaxedQueryChars'=>'[]|{}^&#x5c;&#x60;&quot;&lt;&gt;'
},

**Comment by nambrosch** [comment]
this workaround works, thank you.  i'll keep an eye out for the next update.
```
    proxy          => {
      proxyName         => 'mysite.com',
      proxyPort         => '443',
      relaxedPathChars  => '[]|',
      relaxedQueryChars => '[]|{}^&#x5c;&#x60;&quot;&lt;&gt;',
      scheme            => 'https',
},
```

**Comment by mcruzmetrostar** [comment]
BUMP for this issue, this change is also needed on JIRA 7.13.0

**Comment by bastelfreak** [comment]
Hi @nambrosch or @mcruzmetrostar, could one of you provide a PR for this?

**Comment by mojibake-umd** [comment]
This was actually added in f6bd5405ec50ae5e444a38a869b7b647d9764ff9 so this can get closed?

**Comment by nambrosch** [comment]
@mojibake-umd yes, i've been using module version 4.0.0 since june 20th and it works fine.
