### ISSUE TITLE
Oracle real url has : instead of /

### ISSUE THREAD

**Issue by negast** [voxpupuli/puppet-jira#283]
in  init.pp line234
 'oracle' => "jdbc:${db}:thin:@${dbserver}:${dbport_real}:${dbname}",
should be  'oracle' => "jdbc:${db}:thin:@${dbserver}:${dbport_real}/${dbname}",
 Or this is the case at least in our environment

**Comment by bastelfreak** [comment]
@negast thanks for reporting this. Are you able to provide a pull request with a fix?

**Comment by negast** [comment]
Pull request: https://github.com/voxpupuli/puppet-jira/pull/284
