### ISSUE TITLE
download url has changed

### ISSUE THREAD

**Issue by nambrosch** [voxpupuli/puppet-jira#285]
download url has changed -

old: https://downloads.atlassian.com/software/jira/downloads/
new: https://product-downloads.atlassian.com/software/jira/downloads/

**Comment by nambrosch** [comment]
also the download_url parameter should not contain a trailing slash.

**Comment by alexjfisher** [comment]
@nambrosch Thanks for reporting this.  Would you be able to open a PR to fix?

**Comment by alexjfisher** [comment]
Actually, looks like someone else is already on the case.
https://github.com/voxpupuli/puppet-jira/pull/281
