### ISSUE TITLE
systemd provider has incorrect file-mode

### ISSUE THREAD

**Issue by vanElden** [voxpupuli/puppet-jira#289]
## How to reproduce (e.g Puppet code you use)
Install Jira on host with systemd.

## What are you seeing
At every startup the following warning is logged:
"Configuration file /lib/systemd/system/jira.service is marked executable. Please remove executable permission bits. Proceeding anyway.".

## What behaviour did you expect instead
Startup without warnings.

## Output log
See above.

**Comment by oranenj** [comment]
This seems to have been fixed, closing this issue.
