### ISSUE TITLE
Jira downloads url default

### ISSUE THREAD

**Issue by GrayPockets** [voxpupuli/puppet-jira#294]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2018.1.4
- Distribution: Ubuntu 16.04
- Module version: 3.5.2

## How to reproduce (e.g Puppet code you use)
Use the module with default download_url

## What are you seeing
The module fails to download Jira archive

## What behaviour did you expect instead
The module downloads Jira archive (then installs it)

### With original Url
change from 'absent' to 'present' failed: Execution of '/usr/bin/curl https://downloads.atlassian.com/software/jira/downloads//atlassian-servicedesk-3.15.1.tar.gz -o /tmp/atlassian-servicedesk-3.15.1.tar.gz_20190416-3720-837d1c -fsSL --max-redirs 5' returned 22: curl: (22) The requested URL returned error: 404 Not Found

## Any additional information you'd like to impart
Recently it appears that Jira has moved its download location from https://downloads.atlassian.com/software/jira/downloads/ to https://product-downloads.atlassian.com/software/jira/downloads/

I suggest we update the default download_url

**Comment by towo** [comment]
Can confirm, just happened upon this myself.

**Comment by towo** [comment]
Well, @alexjfisher already fixed this in #286; it'll be in the next release. You can use the git version until then (`mod puppet/jira, :git => https://github.com/voxpupuli/puppet-jira` in a `Puppetfile`).
