### ISSUE TITLE
Java 11 Compatibility

### ISSUE THREAD

**Issue by nambrosch** [voxpupuli/puppet-jira#300]
This parameter breaks compatibility with jdk11 -

https://github.com/voxpupuli/puppet-jira/blob/a40b36fbb8631d889b8691ff9e7aa51ad1d23ab5/templates/setenv.sh.erb#L50

Here is the exception -

```
Unrecognized VM option 'PrintGCDateStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
```

Emptying this option allows Jira to start.

**Comment by wolfaba** [comment]
any temporary workaround for this issue until the update is released? thank you!

**Comment by nambrosch** [comment]
@wolfaba i believe adding `-XX:+IgnoreUnrecognizedVMOptions` to `java_opts` should help.

**Comment by wolfaba** [comment]
@nambrosch Perfect! It works! Cool backward compatibility option :smile: Thank you very much!
