### ISSUE TITLE
JVM_CODE_CACHE_ARGS not set

### ISSUE THREAD

**Issue by mojibake-umd** [voxpupuli/puppet-jira#308]
According to [upgrade notes for 7.13.x](https://confluence.atlassian.com/jirasoftware/jira-software-7-13-x-upgrade-notes-957135908.html) JVM_CODE_CACHE_ARGS should be set.
This option is missed because setenv.sh is delivered via ERB template.

I was able to work around this setting in Hiera.
jira::java_opts: '-XX:InitialCodeCacheSize=32m -XX:ReservedCodeCacheSize=512m -Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory'

InterningDocumentFactory is another missing option, for which I will create a separate issue, #309 .

**Comment by oranenj** [comment]
This is fixed in current master
```
setenv.sh.erb:JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=32m -XX:ReservedCodeCacheSize=512m <%= @jvm_codecache_args %>'
```
