### ISSUE TITLE
Bump puppetlabs-stdlib dependency

### ISSUE THREAD

**Issue by h-haaks** [voxpupuli/puppet-jira#318]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.x, 6.x
- Ruby:
- Distribution:
- Module version: 4.0.0

## What are you seeing
Dependecy conflicts with other updated modules

## What behaviour did you expect instead
I expect the latest version of this module to be compatible with the latest versions of its dependencies.

## Any additional information you'd like to impart
I did not add puppet-archive to this issue since it is requested in issue #304 
I Also think its about time to remove the deprecated puppet-staging dependency..

**Comment by ekohl** [comment]
Fixed in 78052cd8bc317c018c41d61590a00dc02b5dbcad
