### ISSUE TITLE
Release v5.2.0

### ISSUE THREAD

**Issue by danifr** [voxpupuli/puppet-jira#409]
Hi @bastelfreak, hope you are doing fine!
Do you think it makes sense to release a v5.2.0 of this module including all the changes we have in master?

I can work on it if you want :) are there some docs on how to do it (for the CHANGELOG and such) ?

Thanks a lot.

**Comment by bastelfreak** [comment]
Hi,
I'm currently not sure if the CI pipeline works. That's a requirement for a new release. If you want you can create a release PR as described in https://voxpupuli.org/docs/releasing_version/
