### ISSUE TITLE
cluster.properties.epp - soon to be deprecated code by Puppet 8

### ISSUE THREAD

**Issue by koogled** [voxpupuli/puppet-jira#411]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Ver 8
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

File: templates/cluster.properties.epp

The soon to be release version 8 of puppet will make the line:
jira.node.id = <%= $facts['fqdn'] %>  As this fact will not work.

**Comment by h-haaks** [comment]
Fixed by #408

**Comment by h-haaks** [comment]
Fixed by #408
