### ISSUE TITLE
JIRA can't parse the JVM arguments when delimited with spaces instead of semicolons.

### ISSUE THREAD

**Issue by zachdaniel** [voxpupuli/puppet-jira#44]
Due to the way the jvm arguments are passed in, JIRA doesn't parse them correctly.  The JVM handles them just fine, but JIRA doesn't understand them properly (as I understand it).  If you look at the support ticket [here](https://confluence.atlassian.com/display/JIRAKB/Setting+Java+parameters+for+Windows+Service+is+causing+Startup+problems+or+not+being+recognized?showComments=true&showCommentArea=true#addcomment), you can see that they want them delimited with semi-colons.  It appears to be a harmless error, but would help clean up a consistent log WARN.

``` erb
JVM_REQUIRED_ARGS="-Djava.awt.headless=true -Datlassian.standalone=JIRA -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dmail.mime.decodeparameters=true"
```

**Comment by zachdaniel** [comment]
I also have an idea/question for you on a unrelated topic, if you don't mind me emailing you.

**Comment by mkrakowitzer** [comment]
Hi Zach

The JVM_REQUIRED_ARGS is hard coded, its a direct copy of what comes from the atlassian install file. That being said I think you are more dilliegent at checking your logs than I am :), so let me verify the warning in the log file and then I will apply a fix. This may potentially be an issue with other variables used by the JVM, such as JVM_SUPPORT_RECOMMENDED_ARGS and JAVA_OPTS, will confirm and apply fix if required. Errors in the startup log files are not desirable :)

The support ticket specifically refers to Windows, can you confirm your operating system for me please.

Thank you for reporting the issue, will resolve it soon.

Please feel free to email me merritt at krakowitzer dot com re your unrelated question, although an issue might be more appropriate, that way we can get more eyes / comments on it.

**Comment by zachdaniel** [comment]
It refers to the windows operating system, but we are deploying on CentOS.  I believe that the statement that this happens 'because you are running JIRA as a Windows service' is false, and that they believe those circumstances to be the only case in which this issue arises.  It probably has something to do with those parameters placement in the windows install documentation, but honestly I couldn't say.

**Comment by jyaworski** [comment]
@mkrakowitzer ping. Is this still an issue?

**Comment by oranenj** [comment]
I'm doing issue cleanup. If this is still a problem, open a new ticket.
