### ISSUE TITLE
Validate all parameters

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-jira#49]
All parameters should be validated. 

Although its going to make a huge mess in the init.pp

**Comment by jyaworski** [comment]
Do you mean validate_*? I agree.

**Comment by dhoppe** [comment]
I think we should cleanup ```voxpupuli/stash``` and use this as baseline for ```voxpupuli/confluence``` and ```voxpupuli/jira```.

**Comment by igalic** [comment]
@dhoppe do it so, :hash: :one:

**Comment by oranenj** [comment]
Types in master now, not needed anymore.
