### ISSUE TITLE
jira::facts cannot access $jira::tomcatPort

### ISSUE THREAD

**Issue by chihoko** [voxpupuli/puppet-jira#63]
In the class params for **jira::facts** you default **$port** to **$jira::tomcatPort** however this variable is not accessible from **jira::facts** so it defaults to nothing and I get the error _Fact file /etc/facter/facts.d/jira_facts.rb was parsed but returned an empty data set_. I know I can override it when declaring the class, but its a bug nonetheless.

```
class jira::facts(
  $ensure = 'present',
  $port   = $jira::tomcatPort,
  $uri    = '127.0.0.1',
) {
```

**Comment by mkrakowitzer** [comment]
We set $tomcatPort = 8080, in the init.pp.

**Comment by chihoko** [comment]
Yes but init.pp doesn't call ::jira::facts so it can't access $tomcatPort. 
If I **don't** explicitly set $port when declaring the facts class i.e.

    class { '::jira::facts':
      port => '8080',
    }

then **/etc/facter/facts.d/jira_facts.rb** looks like:
```
require 'json'
require 'open-uri'
begin
  url = 'http://127.0.0.1:/rest/api/2/serverInfo'
  info = open(url, &:read)
rescue
  exit 0
end
.....
```

**Comment by mkrakowitzer** [comment]
Strange, we are sourcing the value from the main class.  $port   = $jira::tomcatPort,
You can confirm you are calling the main class? So your manifest should be something like:

class {'jira': }
class { 'jira::facts': }

I added a test for this, and it is detecting the port value from the main class. Assuming you are doing the above, can you confirm your version of puppet and ruby?

**Comment by chihoko** [comment]
My apologies, I had jira::facts declared before the main class so $port wasn't available when jira::facts was declared. I don't know if this is worth pointing out in the docs.

Thanks for the awesome module and quick upgrade to 6.4 today!

**Comment by mkrakowitzer** [comment]
For the next release jira::facts will be a private class and included by default. I recently did this for the stash module and noone has complained :)

 Thanks for taking the time to log issues btw, I do appreciate it.

If its not to much trouble, please rate the module on the forge (Thanks in advance).
