### ISSUE TITLE
consolidate db, dbtype, and dbdriver

### ISSUE THREAD

**Issue by tedivm** [voxpupuli/puppet-jira#73]
Right now you have to set three configs in order to accomplish the switching between one database type and another. I think it makes far more sense to change the dbtype and dbdriver values based off of what people set for db.

**Comment by mkrakowitzer** [comment]
+1, agree 100%

**Comment by nathonfowlie** [comment]
Another up vote for this one. I only skimmed through the documentation and was quite confused when it was defaulting to Postgres despite the fact I'd set dbtype and dbdriver. Would be good to pivot off the "dbtype" setting to select the appropriate driver and default port (but keep the dbport option for non-standard configurations).

**Comment by TJM** [comment]
Agreed, make the defaults `undef` then when its being used, test if its undef, and use a reasonable default based on `$jira::db` (which seems to be the switch for other parameters)
