### ISSUE TITLE
Add support to configure AJP as the only enabled connector

### ISSUE THREAD

**Issue by tohuwabohu** [voxpupuli/puppet-jira#85]
Running JIRA behind an Apache reverse proxy enables the usage of [AJP](https://tomcat.apache.org/tomcat-4.0-doc/config/ajp.html) to do all communication via the AJP rather than HTTP. Unfortunately, the module still requires to configure the regular tomcat HTTP connector.

Being able to disable the HTTP connector and only use the AJP one would make the configuration a bit cleaner.

**Comment by igalic** [comment]
how so?

**Comment by tohuwabohu** [comment]
> how so?

* one less connector so simpler server.xml, 
* one less open port on the host, 
* one less parameter that I have to specify in order to make sure the port is bound to localhost only and not accessible from the internet

**Comment by igalic** [comment]
okay.

would you like to submit a patch?

**Comment by tohuwabohu** [comment]
Assuming I would remove the connector. The custom fact which is revealing the current JIRA version would then have to talk to the Apache sitting in front of JIRA.

Do you think adding support for HTTPS is the only thing that's missing (besides dealing with self-signed certificates)? Or are there other things that could break?
