### ISSUE TITLE
Upgrade to Jira Software v7

### ISSUE THREAD

**Issue by chihoko** [voxpupuli/puppet-jira#95]
Does the module support upgrading to v7 yet? If not are there any plans to support v7 in the near future?

**Comment by mkrakowitzer** [comment]
There is a pull request in progress to add support for V7 and puppet 4. Hopefully wont be to long now.

**Comment by Conzar** [comment]
Well, Jira 7 apparently doesn't have a zip format available for download.  Its only a .bin file.  I don't know why they went this route --- maybe reducing the number of builds is easier for them at this point?

**Comment by mkrakowitzer** [comment]
Its available here, new naming convention though :(
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.0.0-jira-7.0.0.tar.gz

**Comment by jared-di** [comment]
JIRA Core
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-7.0.0.tar.gz

JIRA Software (JIRA + Agile)
https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.0.0-jira-7.0.0.tar.gz

JIRA Service Desk (JIRA + Service Desk)
https://downloads.atlassian.com/software/jira/downloads/atlassian-servicedesk-3.0.0-jira-7.0.0.tar.gz

**Comment by jared-di** [comment]
@mkrakowitzer, is there an ETA when JIRA 7 support will be available?

**Comment by xtra-be** [comment]
any progress on this one?
what are the blocking issue's?

**Comment by igalic** [comment]
from what i understand, @mkrakowitzer is currently in a cave working on this, and stash → bitbucket

**Comment by jUsjDnr9vNok4kelSGyl** [comment]
Any progress on this? I'm tempted to just install manually from the Atlassian package soon.

**Comment by spacepants** [comment]
@jUsjDnr9vNok4kelSGyl v7 support was added in #107.

**Comment by Conzar** [comment]
So when is the next release which will include v7 support?

**Comment by pdirksen** [comment]
Please merge the related pull request.

**Comment by igalic** [comment]
closing with #107 merged
